import type { Metadata } from "next";
import localFont from "next/font/local";
import { Stack } from "@mui/material";
import "./globals.css";
import SideBar from "@/components/side-bar";
const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};



export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Stack direction="row" className="h-screen divide-x divide-slate-400/25">
					<SideBar/>
					<div className="content-page w-full">
						<div>
							{children}
						</div>
					</div>
				</Stack>


			</body>
		</html>
	);
}
